[servers]
100.97.87.120 ansible_user=admin ansible_ssh_private_key_file=/Users/matthew/.ssh/vgio ansible_ssh_common_args='-o StrictHostKeyChecking=no'
100.67.164.92 ansible_user=admin ansible_ssh_private_key_file=/Users/matthew/.ssh/vgio ansible_ssh_common_args='-o StrictHostKeyChecking=no'
